apiVersion: v1
kind: Pods
metadata:
  name: WordPress+MySQL
spec:
  restartPolicy: Always
  volumes:
  - name: db_data
    emptyDir: {}
  - name: wordpress_data
    emptyDir: {}
  containers:
  - name: mysql
    image: mysql:5.7
    volumeMounts:
    - name: db_data
      mountPath: /var/lib/mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "somewordpress"
    - name: MYSQL_DATABASE
      value: "wordpress"
    - name: MYSQL_USER
      value: "wordpress"
    - name: MYSQL_PASSWORD
      value: "wordpress"
  - name: wordpress
    image: wordpress:php8.1-fpm
    volumeMounts:
    - name: wordpress_data
      mountPath: /var/www/html
    ports:
      port: 8087
      targetPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      value: "db"
    - name: WORDPRESS_DB_USER
      value: "wordpress"
    - name: WORDPRESS_DB_PASSWORD
      value: "wordpress"
    - name: WORDPRESS_DB_NAME
      value: "wordpress"
